name: aroma_mobile
description: "Aroma Mobile"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  j1_core_base:
    git:
      url: https://github.com/J1-Apps/j1_core.git
      path: packages/j1_core_base
      ref: v1.0.0

  j1_core_firebase:
    git:
      url: https://github.com/J1-Apps/j1_core.git
      path: packages/j1_core_firebase
      ref: v1.0.0

  get_it: ^8.0.3
  intl: ^0.20.2
  package_info_plus: ^8.3.0
  flutter_bloc: ^9.1.1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  bloc_concurrency: ^0.3.0
  vector_graphics: ^1.1.18
  supabase_flutter: ^2.9.1
  firebase_core_platform_interface: ^5.4.0
  google_sign_in: ^6.3.0
  dart_mappable: ^4.5.0
  collection: ^1.19.1
  go_router: ^15.1.2
  bloc_event_transformers: ^2.0.0
  envied: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
      
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  mocktail: ^1.0.4
  vector_graphics_compiler: ^1.1.17
  dart_mappable_builder: ^4.5.0
  envied_generator: ^1.1.1
  mocktail_image_network: ^1.2.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - path: assets/vector/logo/
      transformers:
        - package: vector_graphics_compiler

  fonts:
    - family: JamIcons
      fonts:
        - asset: packages/j1_core_base/j1_ui/fonts/JamIcons.ttf

    - family: Crimson Text
      fonts:
        - asset: fonts/crimson_text/CrimsonText-Regular.ttf
        - asset: fonts/crimson_text/CrimsonText-Italic.ttf
          style: italic
        - asset: fonts/crimson_text/CrimsonText-Bold.ttf
          weight: 700
        - asset: fonts/crimson_text/CrimsonText-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/crimson_text/CrimsonText-SemiBold.ttf
          weight: 600
        - asset: fonts/crimson_text/CrimsonText-SemiBoldItalic.ttf
          weight: 600
          style: italic

    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: fonts/poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
